export const projects = [
  {
    title: 'PurgeAI',
    desc: 'Purge AI is an AI-powered tool that analyzes GitHub PRs using LLMs and metadata extraction. It streamlines developer workflows with accurate labeling, concise summaries, and dynamic adaptation to different repositories, boosting speed, consistency, and review efficiency.',
    srcLink: 'https://github.com/abhub23/purge.ai',
    webLink: 'https://purgeai.abdullahtech.dev',
    skills: [
      'Typescript',
      'React',
      'NextJS',
      'Express',
      'Node JS',
      'OAuth2',
      'Prisma',
      'TailwindCSS',
      'Vercel',
    ],
    imgLink: '/projects/purgeailogo.webp',
  },
  {
    title: 'Privado',
    desc: 'Privado is a fast, secure private chat app powered by Socket.IO. Instantly connect, message friends, and enjoy real-time private conversations with no distractions. Simple, smooth, and built for people who value privacy and speed.',
    srcLink: 'https://github.com/abhub23/Web-Socket-Server-Sets',
    webLink: 'https://privado.abdullahtech.dev',
    skills: [
      'Typescript',
      'React',
      'NextJS',
      'Express',
      'Node JS',
      'Socket.IO',
      'TailwindCSS',
      'Golang',
      'Vercel',
    ],
    imgLink: '/projects/chat.png',
  },
  {
    title: 'Draw',
    desc: 'Draw app that lets you sketch freely with smooth strokes, vibrant colors, and an intuitive interface, delivering a fast, minimal, and immersive digital drawing experience.',
    srcLink: 'https://github.com/abhub23/draw',
    webLink: 'https://draw.abdullahtech.dev/',
    skills: ['Typescript', 'Next js', 'React', 'Canvas', 'TailwindCSS', 'Vercel', 'Zustand'],
    imgLink: '/projects/draw.jpg',
  },
  {
    title: 'Github Metrics',
    desc: "Now you can Compare your Github Stats with the best in the world, be it Torvalds, Karpathy, Harkirat and who not. You think you're doing your best? have better PR's than someone? Lets see here mate.",
    srcLink: 'https://github.com/abhub23/Github-Metrics',
    webLink: 'https://githubstats.abdullahtech.dev',
    skills: ['Typescript', 'React', 'Express', 'TailwindCSS', 'Vite', 'Gemini', 'Zustand'],
    imgLink: '/projects/githublogo.png',
  }
];
